name: "Build and deploy"
on: push
jobs:
  build:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run npm ci
        run: |
          npm install
      - uses: akhileshns/heroku-deploy@v3.12.12
        if: github.ref == 'refs/heads/master'
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: em2021-betpool
          heroku_email: ${{secrets.HEROKU_EMAIL}}
